name: Test Cross-Repo Issue Creation

on:
  workflow_dispatch:

jobs:
  test-create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Create issue in nextversion-action
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_ISSUE_PAT }}
        run: |
          ISSUE_TITLE="Automation test issue from nextversion 🔧"
          ISSUE_BODY=$(cat << EOF

          **THIS IS AN AUTOMATION TEST, PLEASE IGNORE**

          \`nextversion\` had a [new release](https://github.com/tsdtsdtsd/nextversion/releases/latest).

          - [ ] update download path to new binary
          - [ ] any new inputs?
          - [ ] any new outputs?
          - [ ] update README.md

          EOF
          )

          curl -X POST https://api.github.com/repos/tsdtsdtsd/nextversion-action/issues \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -d "$(jq -n --arg title "$ISSUE_TITLE" --arg body "$ISSUE_BODY" --argjson labels '["update"]' \
                  '{title: $title, body: $body, labels: $labels}')"
