name: Test Cross-Repo Issue Creation

on:
  workflow_dispatch:

jobs:
  test-create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Create test issue in nextversion-action
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_ISSUE_PAT }}
        run: |
          ISSUE_TITLE="Test Issue from nextversion 🔧"
          ISSUE_BODY=$(cat << EOF
          ### 🔧 Test Issue
          
          This is a test issue created by a workflow in the \`nextversion\` repo using a \`PAT\`.

          - If you see this, 
          - it worked!
          EOF
          )


          curl -X POST https://api.github.com/repos/tsdtsdtsd/nextversion-action/issues \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -d "$(jq -n --arg title "$ISSUE_TITLE" --arg body "$ISSUE_BODY" \
                  '{title: $title, body: $body}')"