name: Test Cross-Repo Issue Creation

on:
  workflow_dispatch:

permissions:
  issues: write

jobs:
  test-create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Create test issue in nextversion-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ISSUE_TITLE="Test Issue from nextversion"
          ISSUE_BODY="### 🔧 Test Issue

This is a test issue created by a GitHub Actions workflow in the \`nextversion\` repo.

If you see this, cross-repo issue creation works without a PAT. 🎉"

          curl -X POST https://api.github.com/repos/tsdtsdtsd/nextversion-action/issues \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -d "$(jq -n --arg title "$ISSUE_TITLE" --arg body "$ISSUE_BODY" \
                  '{title: $title, body: $body}')"